version: '3.8'

services:
  transporte:
    container_name: transporte
    image: transporte
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
    networks:
      - transporte-prod
    volumes:
      - transporte:/app
    restart: unless-stopped

volumes:
  transporte:

networks:
  transporte-prod:
    name: transporte-prod
    driver: bridge